version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: laundromat_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - laundromat_network

  backend:
    build: ./server
    container_name: laundromat_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - laundromat_network

  frontend:
    build: ./frontend
    container_name: laundromat_frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000" #no ip access via 3000 anymore, use domain name
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - laundromat_network

  adminer:
    image: adminer:latest
    container_name: laundromat_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - laundromat_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  laundromat_network:
    driver: bridge